### ISSUE TITLE
KeyError 'Producible' when running test data

### ISSUE THREAD

**Issue by DennyPopp** [AuReMe/metage2metabo#10]
Hi there,

when running m2m test I get an error message when it comes to "Running minimal community selection": 

`Running minimal community selection
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/m2m", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/metage2metabo/__main__.py", line 337, in main
    main_test(args.out, args.cpu)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/metage2metabo/__main__.py", line 473, in main_test
    padmet_bool, host_mn, targets_file)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/metage2metabo/__main__.py", line 346, in main_workflow
    run_workflow(*allargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/metage2metabo/m2m_workflow.py", line 72, in run_workflow
    metacom_analysis(sbml_dir, out_dir, seeds, host_mn, targets_file)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/metage2metabo/m2m_workflow.py", line 131, in metacom_analysis
    mincom(instance_w_targets, out_dir)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/metage2metabo/m2m_workflow.py", line 280, in mincom
    producible_targets = all_results['producible']
KeyError: 'producible'`

Any idea what might cause this error and how to fix this?

Thanks a lot,
Denny

**Comment by cfrioux** [comment]
Hi Denny, 

Thank you for your message, we will investigate. Could you please tell us the version of M2M you use?

Clémence

**Comment by DennyPopp** [comment]
Hi Clémence,

thanks for your quick reply. 

I am using m2m 1.3.3 which I think is the latest and Miscoto is version 2.1.1

Thanks for looking into this,
Denny

**Comment by cfrioux** [comment]
Hi Denny, 

You need to update MiSCoTo to version 2.1.2 (`pip install -U Miscoto`) and it should solve the problem.
Tell me if it works.

Clémence

**Comment by DennyPopp** [comment]
Hi Clémence,

again many thanks! Updating Miscoto solved the problem! At least m2m test ran without an error. Now I will move on to use my own data. 

Thanks,
Denny

**Comment by cfrioux** [comment]
You are very welcome, happy to help!
