### ISSUE TITLE
"Can't connect to X11 window server using..." m2m_analysis

### ISSUE THREAD

**Issue by cfrioux** [AuReMe/metage2metabo#24]
The following java error occurred for a run of m2m_analysis on HPC:

```
<II> Create SVG ... Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at org.apache.batik.svggen.SVGGraphics2D.<init>(Unknown Source)
	at org.apache.batik.svggen.SVGGraphics2D.<init>(Unknown Source)
	at org.mattlab.eaglevista.ui.GraphImageFactory.getSVGGraphicsOfGraph(GraphImageFactory.java:157)
	at org.mattlab.eaglevista.ui.GraphImageFactory.createImage(GraphImageFactory.java:80)
	at org.mattlab.eaglevista.ui.EvCommandLineInterpreter.runImpl(EvCommandLineInterpreter.java:466)
	at org.mattlab.eaglevista.ui.EvCommandLineInterpreter.main(EvCommandLineInterpreter.java:81)
```

It prevents the powergraph java extension to create the svg file of the powergraph and the program exits with an error.

**Comment by ArnaudBelcour** [comment]
Added troubleshooting in #61.
