### ISSUE TITLE
UnicodeDecodeError when running m2m_analysis with Singularity

### ISSUE THREAD

**Issue by cfrioux** [AuReMe/metage2metabo#25]
The following error was obtained when running m2m_analysis in a Singularity container:

```
######### Creation of the powergraph website accessible at results_m2m_analysis_scfa/html/metabolic_targets_scfa #########
Traceback (most recent call last):
  File "/usr/local/bin/m2m_analysis", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/__main_analysis__.py", line 289, in main
    args.oog, new_arg_modelhost, args.level)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/__main_analysis__.py", line 303, in main_analysis_workflow
    run_analysis_workflow(*allargs)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m_analysis/m2m_analysis_workflow.py", line 48, in run_analysis_workflow
    powergraph_analysis(gml_output, output_dir, oog_jar, taxon_file, taxonomy_level)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m_analysis/graph_compression.py", line 174, in powergraph_analysis
    merge_html_css_js(html_target +'_taxon', output_html_merged)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m_analysis/graph_compression.py", line 473, in merge_html_css_js
    cytoscape_min_js_str =  input_cytoscape_min_js.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 234868: ordinal not in range(128)
```

**Comment by ArnaudBelcour** [comment]
Added troubleshooting in #61.
