### ISSUE TITLE
Progress problem

### ISSUE THREAD

**Issue by ChenCongZ** [AuReMe/metage2metabo#30]
Traceback (most recent call last):
  File "D:\Metage2Metabo\method_tutorial\test", line 3, in <module>
    instance_path, network_scopes = community_scope.cscope('data/community', 'data/seeds.sbml', 'output_folder')
  File "C:\Users\陈聪聪\AppData\Roaming\Python\Python310\site-packages\metage2metabo\m2m\community_scope.py", line 50, in cscope
    community_reachable_metabolites = comm_scope_run(instance_com, out_dir, host)
  File "C:\Users\chen\AppData\Roaming\Python\Python310\site-packages\metage2metabo\m2m\community_scope.py", line 108, in comm_scope_run
    microbiota_scope = run_scopes(lp_instance_file=instance)
  File "C:\Users\chen\AppData\Roaming\Python\Python310\site-packages\miscoto\miscoto_scopes.py", line 171, in run_scopes
    model = query.get_scopes(lp_instance_file, commons.ASP_SRC_SCOPES)
  File "C:\Users\chen\AppData\Roaming\Python\Python310\site-packages\miscoto\query.py", line 34, in get_scopes
    for model in models.discard_quotes.by_arity:
  File "C:\Program Files\Python310\lib\site-packages\clyngor\answers.py", line 205, in __iter__
    for answer_set, optimization, optimality, answer_number in self._answers:
  File "C:\Program Files\Python310\lib\site-packages\clyngor\solving.py", line 231, in _gen_answers
    for payload in validate_clasp_stderr(stderr):
  File "C:\Program Files\Python310\lib\site-packages\clyngor\parsing.py", line 244, in validate_clasp_stderr
    line = next(stderr).strip()
  File "C:\Program Files\Python310\lib\site-packages\clyngor\solving.py", line 115, in <genexpr>
    stderr = (line.decode() for line in clingo.stderr)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 9: invalid start byte

**Comment by ChenCongZ** [comment]
running community scope

**Comment by cfrioux** [comment]
Followup of https://github.com/cfrioux/MeneTools/issues/10

**Comment by cfrioux** [comment]
Hi, you created a new issue for what seems to be the same problem as [https://github.com/cfrioux/MeneTools/issues/10](https://github.com/cfrioux/MeneTools/issues/10). Am I correct?

Did you try the solution @ArnaudBelcour suggested?

Also, we still miss some context: python version, OS...

Are you still trying to run the tutorial?

**Comment by ChenCongZ** [comment]
> 嗨，您为似乎与[cfrioux / MeneTools#10](https://github.com/cfrioux/MeneTools/issues/10)相同的问题创建了一个新问题。我说的对吗？
> 
> 您是否尝试过@ArnaudBelcour建议的解决方案？
> 
> 另外，我们仍然错过了一些上下文：python版本，操作系统...
> 
> 是否仍在尝试运行本教程？

Sorry, I didn't see the news of yesterday's reply. I'm trying to solve this problem with your method.
