### ISSUE TITLE
Multiple errors when running test data

### ISSUE THREAD

**Issue by DafniGi** [AuReMe/metage2metabo#35]
Hello,

I have installed Pathway Tools v25.5 and Metage2Metabo v1.5.0 both locally and with docker. In both cases when I run either `m2m test` or `m2m workflow`, I am getting the following output with error from MiSCoTo:

```
Uncompressing test data to /shared/test_output_directory
Launching workflow on test data
######### Running metabolic network reconstruction with Pathway Tools #########
---------- Launching mpwt ----------
|Input Check|GCA_003433675| Missing flat_files_creation.lisp; genetic-elements.dat; organism-params.dat. Inputs file created for GCA_003433675
|PathoLogic|GCA_003433675| pathway-tools -no-web-cel-overview -no-cel-overview -no-patch-download -disable-metadata-saving -nologfile -patho /shared/test_output_directory/workflow_genomes/GCA_003433675
|Flat files creation|GCA_003433675| pathway-tools -no-patch-download -disable-metadata-saving -nologfile -load /shared/test_output_directory/workflow_genomes/GCA_003433675/flat_files_creation.lisp
|Output Check|/shared/test_output_directory/workflow_genomes/GCA_003433675| 23 out of 23 dat files created.
|Moving output files|GCA_003433675| 
|Input Check|GCA_003433665| Missing flat_files_creation.lisp; genetic-elements.dat; organism-params.dat. Inputs file created for GCA_003433665
|PathoLogic|GCA_003433665| pathway-tools -no-web-cel-overview -no-cel-overview -no-patch-download -disable-metadata-saving -nologfile -patho /shared/test_output_directory/workflow_genomes/GCA_003433665
|Flat files creation|GCA_003433665| pathway-tools -no-patch-download -disable-metadata-saving -nologfile -load /shared/test_output_directory/workflow_genomes/GCA_003433665/flat_files_creation.lisp
|Output Check|/shared/test_output_directory/workflow_genomes/GCA_003433665| 23 out of 23 dat files created.
|Moving output files|GCA_003433665| 
|Output Check| 2 on 2 builds have passed!
-------------- Checking mpwt runs --------------
All runs are successful.
-------------- mpwt has finished in 449.76s! Thank you for using it. --------------
######### Creating SBML files #########
######### Stats GSMN reconstruction #########
Number of genomes: 2
Number of reactions in all GSMN: 2220
Number of compounds in all GSMN: 2250
Average reactions per GSMN: 1566.50(+/- 760.14)
Average compounds per GSMN: 1655.50(+/- 696.50)
Average genes per GSMN: 922.50(+/- 499.92)
Average pathways per GSMN: 256.50(+/- 139.30)
Percentage of reactions associated with genes: 72.03(+/- 3.73)
--- Recon runtime 455.74 seconds ---

######### Running individual metabolic scopes #########
Individual scopes for all metabolic networks available in /shared/test_output_directory/indiv_scopes/indiv_scopes.json
2 metabolic models considered.

153 metabolites in core reachable by all organisms (intersection) 

"M_P3I_c"
"M_RIBOSE__45__1P_c"
"M_CPD0__45__2472_c"
...

318 metabolites reachable by individual organisms altogether (union), among which 26 seeds (growth medium) 

"M_N__45__FORMIMINO__45__L__45__GLUTAMATE_c"
"M_P3I_c"
"M_RIBOSE__45__1P_c"
...

intersection of scope 153
union of scope 318
max metabolites in scope 314
min metabolites in scope 157
average number of metabolites in scope 235.50 (+/- 111.02)
Analysis of functional redundancy (producers of all metabolites) is computed as a dictionary in /shared/test_output_directory/indiv_scopes/rev_iscope.json and as a matrix in /shared/test_output_directory/indiv_scopes/rev_iscope.tsv.
--- Indiv scopes runtime 0.75 seconds ---

######### Creating metabolic instance for the whole community #########
Created instance in /shared/test_output_directory/community_analysis/miscoto_v47dbvv5.lp
Running whole-community metabolic scopes
/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:19:14-22: info: atom does not occur in any rule head:
  draft(D)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:22:14-22: info: atom does not occur in any rule head:
  draft(D)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:26:19-28: info: atom does not occur in any rule head:
  target(M)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:27:21-30: info: atom does not occur in any rule head:
  target(M)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:31:16-24: info: atom does not occur in any rule head:
  draft(O)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:42:19-28: info: atom does not occur in any rule head:
  target(M)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:43:21-30: info: atom does not occur in any rule head:
  target(M)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:48:72-80: info: atom does not occur in any rule head:
  draft(O)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:70:51-60: info: atom does not occur in any rule head:
  target(T)

/usr/local/lib/python3.6/dist-packages/miscoto/encodings/scopes.lp:72:51-60: info: atom does not occur in any rule head:
  target(T)

Community scopes for all metabolic networks available in /shared/test_output_directory/community_analysis/comm_scopes.json
--- Community scope runtime 0.71 seconds ---

Added value of cooperation over individual metabolism: 27 newly reachable metabolites: 

"M_UTP_c"
"M_DCDP_c"
"M_CTP_c"
...

Added-value of cooperation written in /shared/test_output_directory/community_analysis/addedvalue.json

Target file created with the addedvalue targets in: /shared/test_output_directory/community_analysis/targets.sbml
Setting 27 compounds as targets 

Running minimal community selection
/usr/local/lib/python3.6/dist-packages/miscoto/encodings/community_soup.lp
Traceback (most recent call last):
  File "/usr/local/bin/m2m", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/__main__.py", line 380, in main
    main_test(args.out, args.cpu)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/__main__.py", line 520, in main_test
    use_pwt_xml)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/__main__.py", line 389, in main_workflow
    run_workflow(*allargs)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m/m2m_workflow.py", line 53, in run_workflow
    metacom_analysis(sbml_dir, out_dir, seeds, host_mn, targets_file, nb_cpu)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m/m2m_workflow.py", line 114, in metacom_analysis
    mincom(instance_w_targets, out_dir)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m/minimal_community.py", line 46, in mincom
    all_results = compute_mincom(instance_w_targets, miscoto_dir)
  File "/usr/local/lib/python3.6/dist-packages/metage2metabo/m2m/minimal_community.py", line 114, in compute_mincom
    output_json=mincom_json_file)
  File "/usr/local/lib/python3.6/dist-packages/miscoto/miscoto_mincom.py", line 216, in run_mincom
    score = one_model[1]
TypeError: 'NoneType' object is not subscriptable
```
Do you have any suggestions as to what might be wrong? Thank you very much.

**Comment by ArnaudBelcour** [comment]
Hi @DafniGi,

The error message indicates that miscoto did not find answers for the dataset which is strange.

I think the error comes from a new version of clyngor (a dependency of MiSCoTo). Some weeks ago, clyngor has been updated to fix an issue with the new python API of clingo but this new version leads to issue with MiSCoTo and MeneTools. With this issue no answers are returned. A first test is to see if your version of the python package clyngor is superior to 0.4.0.

If this is the case, we are currently working on a fix for this issue. Can you try the branches `fix_new_clyngor` of [MiSCoTo](
https://github.com/cfrioux/miscoto/tree/fix_new_clyngor) and [MeneTools](https://github.com/cfrioux/MeneTools/tree/fix_new_clyngor) and see if it fixes the issue?

Best Regards,
Arnaud Belcour.

**Comment by DafniGi** [comment]
Thank you both! I indeed have clyngor 0.4.1. I tried with the branches fix_new_clyngor of MiSCoTo and MeneTools, but I am still getting the same error.

**Comment by cfrioux** [comment]
I am able to reproduce the error with Python 3.8, conda on Ubuntu but I do not fully understand it yet. 
However, I was able to find a combination of python, miscoto and clyngor version that still work well together. I give you my env so you can use m2m while we keep digging.

Are you using conda? If yes:

```
conda create -n miscoto3.7 python=3.7.7
conda activate miscoto3.7
# python -m pip install --upgrade pip --user
pip install clyngor==0.3.31
pip install miscoto
pip install metage2metabo
pip install networkx bubbletools ete3
```

Should do the trick.

**Comment by cfrioux** [comment]
@DafniGi could you `pip freeze` your environment please? And tell us your python version and type of env (conda?) ?

**Comment by cfrioux** [comment]
Finally understood what happened. The current fix on Github still have the same version numbers as the releases so when running the install from the Github branch, nothing actually gets installed (requirement already satisfied).
If you uninstall menetools and miscoto first (`pip uninstall miscoto menetools`) and then install the fix (`pip install git+https://github.com/cfrioux/menetools.git@fix_new_clyngor`and `pip install git+https://github.com/cfrioux/miscoto.git@fix_new_clyngor`), it works properly. 
We'll update the version numbers and make the releases very soon.

**Comment by cfrioux** [comment]
Menetools v. 3.2.2 and Miscoto v3.1.2 are released and should fix the problems.

**Comment by DafniGi** [comment]
Thank you very much for the prompt responses.  Menetools v. 3.2.1 was the latest version I could find, and it worked.
For the record in case it is useful in the future, I was in CentOS and I wasn't using conda.
