### ISSUE TITLE
No /home/chencong/.ncbirc file, please fix it before using the program

### ISSUE THREAD

**Issue by ChenCongZ** [AuReMe/metage2metabo#47]
Hi @Clémence Frioux,
This question arises when I reconstruct the metabolic network. I checked my home directory with this filename.
(base) chencong@chencong-QiTianM428-A606:~$ m2m recon -g /home/chencong/test -o /home/chencong/output -c 1
######### Running metabolic network reconstruction with Pathway Tools #########
No /home/chencong/.ncbirc file, please fix it before using the program
(base) chencong@chencong-QiTianM428-A606:~$ ls -a
.              .config    output                   ptools-local
..             Desktop    output1                  Public
AIC-prefs      Documents  output2                  .python_history
anaconda3      Downloads  output3                  snap
.bash_history  .gnupg     PathoLogic-Console-Logs  .sudo_as_admin_successful
.bash_logout   .local     .pathway-tools           Templates
.bashrc        .mozilla   pathway-tools            test
.cache         Music      Pictures                 Videos
.conda         .ncbirc    .profile

**Comment by cfrioux** [comment]
Can you show the content of this file please?

https://metage2metabo.readthedocs.io/en/latest/install.html#requirements-and-installation

**Comment by ChenCongZ** [comment]
Hi @cfrioux,
I fixed this error. However, this problem always arises.
(base) chencong@chencong-QiTianM428-A606:~$ m2m recon -g /home/chencong/pitmud -o /home/chencong/output5 -c 1
######### Running metabolic network reconstruction with Pathway Tools #########
---------- Launching mpwt ----------
Check and delete unfinished builds of Pathway Tools.
Traceback (most recent call last):
  File "/home/chencong/anaconda3/bin/m2m", line 8, in <module>
    sys.exit(main())
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/__main__.py", line 371, in main
    main_recon(args.genomes, args.out, args.noorphan, args.padmet, args.level, args.cpu,
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/__main__.py", line 401, in main_recon
    pgdbdir, sbmldir, padmet_folder= recon(*allargs)
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/m2m/reconstruction.py", line 62, in recon
    pgdb_dir = genomes_to_pgdb(inp_dir, out_dir, nb_cpu,
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/m2m/reconstruction.py", line 159, in genomes_to_pgdb
    multiprocess_pwt(genomes_dir, pgdb_dir,
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/mpwt/mpwt_workflow.py", line 158, in multiprocess_pwt
    independent_mpwt(input_folder, output_folder, patho_inference,
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/mpwt/mpwt_workflow.py", line 357, in independent_mpwt
    run_patho_flat_ids, run_flat_ids = check_input_and_existing_pgdb(run_ids, input_folder, output_folder, number_cpu_to_use)
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/mpwt/pathologic_input.py", line 169, in check_input_and_existing_pgdb
    pathologic_string = pathologic_log.read()
  File "/home/chencong/anaconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 186820: invalid start byte

**Comment by ChenCongZ** [comment]
Hi @cfrioux, @ArnaudBelcour,
When I was creating pictures, I ran into this problem. Can you tell what caused this error?
(base) chencong@chencong-QiTianM428-A606:~$ m2m_analysis graph -j /hone/chencong/output11/json -t /home/chencong/targets_toy.sbml -o /home/chencong/output12
Traceback (most recent call last):
  File "/home/chencong/anaconda3/bin/m2m_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/__main_analysis__.py", line 302, in main
    main_graph(args.json, args.targets, args.out, args.taxon, args.level)
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/__main_analysis__.py", line 324, in main_graph
    graph_analysis(*allargs)
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/m2m_analysis/solution_graph.py", line 58, in graph_analysis
    create_gml(json_paths, target_paths, output_dir, taxonomy_output_file)
  File "/home/chencong/anaconda3/lib/python3.9/site-packages/metage2metabo/m2m_analysis/solution_graph.py", line 109, in create_gml
    with open(json_paths[target_category]) as json_data:
KeyError: 'targets_toy'

**Comment by ChenCongZ** [comment]
I fixed it while entering. I would like to ask how this file(--oog Oog.jar) was generated, since I didn't find it in the directory I got.
